# Generated by Django 4.2.1 on 2026-01-04 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('deadline', models.DateTimeField()),
                ('priority', models.CharField(choices=[('L', 'Низкий'), ('M', 'Средний'), ('H', 'Высокий')], default='M', max_length=1)),
                ('status', models.CharField(choices=[('NS', 'Не начато'), ('IP', 'В работе'), ('DN', 'Сделано')], default='NS', max_length=2)),
            ],
            options={
                'verbose_name': 'Задача',
                'verbose_name_plural': 'Задачи',
                'ordering': ['-priority', 'deadline'],
            },
        ),
    ]
